### ISSUE TITLE
Different color in Panel Window (Material UWU)

### ISSUE THREAD

**Issue by Wilson-Smith** [NyarchLinux/NyarchCustomize#1]
Hello there,

I've recently changed my wallpaper that I had for a bit.
When I changed it the color remained the old color in the top panel window (the window that comes out when you click on the icon in top right), meanwhile the system adopted the new color.

It isn't a big issue, but still a problem.

I tried to restart with and without the Material UwU checked, but still it has remained its color.

I'm on a NVIDIA Driver, I don't know if it could be an issue, but I read it could make some trouble

**Comment by Wilson-Smith** [comment]
After a day, it was totally of another color, then I restarted and the colors were like my background.

I don't know what could have happened, but just auto-fix for me.

If there is an explanation, or a fix to this little problem, I'm here to listen.

I don't close it, so anyone can still see and fix this strange bug.

Anyway, thanks to making god's work!

**Comment by Wilson-Smith** [comment]
After a week, here I am with the same issue...

The color do not match any case the background.

So, again, it wasn't autofixed, and so I don't know why this

**Comment by FrancescoCaracciolo** [comment]
Likely fixed now
